#!/bin/bash
#TARRGET="remote"
#TARRGET="gamepad"
TARRGET="usbcom"

make -C $TARRGET clean
make -C $TARRGET all
st-flash erase
xfce4-terminal -e "st-util -p 5555 -n" --tab -e "gdb-multiarch --init-command="$TARRGET/init_gdb" result/$TARRGET.elf"
