Usage Page (Generic Desktop),
Usage (Joystick),
Collection (Application),
Usage Page (Generic Desktop),
Usage (Pointer),
Collection (Physical),
Logical Minimum (-127),
Logical Maximum (127),
Report Size (8),
Report Count (2),
Push,
Usage (X),
Usage (Y),
Input (Data, Variable, Absolute),
Usage (Hat switch),
Logical Minimum (0),
Logical Maximum (3),
Physical Minimum 0),
Physical Maximum (270),
Unit (Degrees),
Report Count (1),
Report Size (4),
Input (Data, Variable, Absolute, Null State),
Logical Minimum (0),
Logical Maximum (1),
Report Count (2),
Report Size (1),
Usage Page (Buttons),
Usage Minimum (Button 1),
Usage Maximum (Button 2),
Unit (None),
Input (Data, Variable, Absolute)
End Collection,
Usage Minimum (Button 3),
Usage Minimum (Button 4),
Input (Data, Variable, Absolute),
Pop,
Usage (Throttle),
Report Count (1),
Input (Data, Variable, Absolute),
End Collection
